export type SongTitle =
  | 'Introduction Part 1'
  | 'Introduction Part 2'
  | 'Introduction Part 3'
  | 'Get Ready!'
  | 'Dangerous Choice'
  | 'Forward'
  | 'Fractal Froth'
  | 'Flametongue'
  | 'Chiller'
  | 'Determination'
  | 'Amusement'
  | 'Capricious Calculation'
  | 'Mischief or Madness'
  | 'Fight or Flight'
  | 'Menace'
  | 'Dying Light'
  | 'Death Coil'
  | 'Conviction'
  | 'Epilogue'
  | 'Credits'
  | 'Game Over'
  | 'GIVE!'
  | 'Victory Stinger 1'
  | 'Victory Stinger 2'
  | 'Fail Stinger 1'
  | 'Fail Stinger 2'
  | 'click1'
  | 'click2'
  | 'click3'
  | 'click4'
  | 'click5';
