import type { SongTitle } from "@/types/song-title";

export const songMap: Record<SongTitle, string> = {
    'Introduction Part 1': '/music/Ogg/1. Introduction Part 1.ogg',
    'Introduction Part 2': '/music/Ogg/1. Introduction Part 2.ogg',
    'Introduction Part 3': '/music/Ogg/1. Introduction Part 3.ogg',
    'Get Ready!': '/music/Ogg/2. Get Ready!.ogg',
    'Dangerous Choice': '/music/Ogg/3. Dangerous Choice.ogg',
    'Forward': '/music/Ogg/4. Forward.ogg',
    'Fractal Froth': '/music/Ogg/5. Fractal Froth.ogg',
    'Flametongue': '/music/Ogg/6. Flametongue.ogg',
    'Chiller': '/music/Ogg/7. Chiller.ogg',
    'Determination': '/music/Ogg/8. Determination.ogg',
    'Amusement': '/music/Ogg/9. Amusement.ogg',
    'Capricious Calculation': '/music/Ogg/10. Capricious Calculation.ogg',
    'Mischief or Madness': '/music/Ogg/11. Mischief or Madness.ogg',
    'Fight or Flight': '/music/Ogg/12. Fight or Flight.ogg',
    'Menace': '/music/Ogg/13. Menace.ogg',
    'Dying Light': '/music/Ogg/14. Dying Light.ogg',
    'Death Coil': '/music/Ogg/15. Death Coil.ogg',
    'Conviction': '/music/Ogg/16. Conviction.ogg',
    'Epilogue': '/music/Ogg/17. Epilogue.ogg',
    'Credits': '/music/Ogg/18. Credits.ogg',
    'Game Over': '/music/Ogg/19. Game Over.ogg',
    'GIVE!': '/music/Ogg/20. GIVE!.ogg',
    'Victory Stinger 1': '/music/Ogg/21. Victory Stinger 1.ogg',
    'Victory Stinger 2': '/music/Ogg/22. Victory Stinger 2.ogg',
    'Fail Stinger 1': '/music/Ogg/23. Fail Stinger 1.ogg',
    'Fail Stinger 2': '/music/Ogg/24. Fail Stinger 2.ogg',
    'click1': '/music/Ogg/click1.wav',
    'click2': '/music/Ogg/click2.wav',
    'click3': '/music/Ogg/click3.wav',
    'click4': '/music/Ogg/click4.wav',
    'click5': '/music/Ogg/click5.wav',
  };
  